# Generated by Django 4.2.16 on 2024-11-03 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='context',
            new_name='content',
        ),
    ]
